### ISSUE TITLE
Project discontinued?

### ISSUE THREAD

**Issue by poeAddict** [C485/C485.PoE.GGPK#2]
Hi there!
Is this project discontinued?
If not, can you provide a write back function, to make changes to ggpk on the fly?
Or replace like other ggpk tools out there.
Thank you!

**Comment by C485** [comment]
Yes, at least for now, i stopped playing PoE (i found out that i have better things to do :) )
There was no plan for having a "write" option in this library, it's agains PoE terms of use.

But if you want to do it by your self, i think the best and fastest option will be to write a Free region in place of data that you want to modify and add the new data at the end of the file.
